src/Perpustakaan/AnseraBundle/Entity/Anggota.php
<?php

namespace Perpustakaan\AnseraBundle\Entity;

use Doctrine\ORM\Mapping AS ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 *
 * @ORM\Entity
 * @ORM\Table(name="anggota")
 */
class Anggota
{
	/* Entity Field Definitions */

	/**
	 * @ORM\Id
	 * @ORM\Column(type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	protected $id;

	/**
	 * @ORM\Column(type="string",length=100)
	 */
	protected $nama;


	/**
	 * @ORM\Column(type="date",name="tanggal_bergabung")
  	 * @var \DateTime
	 */
	protected $tanggal_bergabung;

	/**
	 * @ORM\Column(type="integer",name="no_telepon")
	 */
	protected $no_telepon;

	/**
	 * @ORM\Column(type="text",name="alamat")
	 */
	protected $alamat;

	/**	 
     * @ORM\OneToMany(targetEntity="Peminjaman", mappedBy="anggota")
	 */
	protected $peminjaman;

	/**	 
     * @ORM\OneToMany(targetEntity="Pengembalian", mappedBy="anggota")
	 */
	protected $pengembalian;
		
	/* Getters & Setters */

	/**
	 * Return the Id
	 */
	public function getId() {
		return $this->id;
	}

	public function getNama() {
		return $this->nama;
	}

	public function getNoTelepon() {
		return $this->no_telepon;
	}

	public function getAlamat() {
		return $this->alamat;
	}

	public function getPengembalian() {
		return $this->pengembalian;
	}

	public function getPeminjaman(){
		return $this->peminjaman;
	}

	public function getTanggalBergabung() {
		return $this->tanggal_bergabung;
	}

	public function addPeminjaman(Peminjaman $peminjaman){
		$this->peminjaman->add($peminjaman);
		return $this;
	}
	
	public function setNama($nama) {
		$this->nama = $nama;
		return $this;
	}

	public function setTanggalBergabung() {
		$this->tanggal_bergabung = new \DateTime("now");

		return $this;
	}
	
	public function setNoTelepon($no_telepon){
		$this->no_telepon=$no_telepon;
		return $this;
	}
	
	public function setAlamat($alamat){
		$this->alamat=$alamat;
		return $this;
	}

	public function addPengembalian(Pengembalian $pengembalian){
		$this->pengembalian->add($pengembalian);

		return $this;
	}

}

src/Perpustakaan/AnseraBundle/Controller/AnggotaController.php
<?php

//nama bundle yang dipakai
namespace Perpustakaan\AnseraBundle\Controller;

//component symfony 
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response; 

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;

//digunakan untuk annotation seperti contoh dibawah yaitu entityManager
use JMS\DiExtraBundle\Annotation as DI;
use JMS\SecurityExtraBundle\Annotation\Secure;

//entity yang digunakan
use Perpustakaan\AnseraBundle\Entity\Buku;

//untuk memudahkan mengarahkan template yang dipakai
use FOS\RestBundle\Controller\Annotations as FOS;

//include service yg yang digunakan
use Perpustakaan\AnseraBundle\Service\AnggotaService;


class AnggotaController 
{
    /**
     * @DI\Inject("doctrine.orm.entity_manager")
     */
    public $entityManager;

    /**
     * @DI\Inject("knp_paginator")
     */
    public $paginator;

    /**
     * @DI\Inject("perpus.service.anggota")
     */
    public $anggotaService;

    /**
     * @DI\Inject("session")
     */
    public $session;

    /**
     * @DI\Inject("router")
     */
    public $router;
	
    /**
     * @Route("/anggota", name="anggota")
     * @Route("/anggota/edit/{id_anggota}", name="anggota_edit")
     * @Route("/anggota/delete/error", name="anggota_delete_error")
     * @Method({"GET","POST"})
     * @FOS\View("PerpustakaanAnseraBundle:Anggota:anggota.html.twig")
     */
    public function anggotaAction(Request $request,$id_anggota="") {
		 $currentRoute = $request->attributes->get('_route');

        //1.untuk menampilkan data di tabel 
        $anggota=$this->anggotaService->getAnggota();
        //pada saat /anggota dipanggil, textbox noTelepon dan nama berisi kosong
        $error="";
        $noTelepon="";
        $alamat="";
        $nama="";
        //2. menentukan method post atau get
        $method=$request->getMethod();
        //3. jika ada id_anggota berarti dianggap edit
        if(!empty($id_anggota)){

            //untuk mengambil data sesuai id_anggota
            $anggotaById=$this->anggotaService->getAnggota($id_anggota);
            
            $noTelepon=$anggotaById["noTelepon"];
            $alamat=$anggotaById["alamat"];
            $nama=$anggotaById["nama"];
        }

        //4.jika pengguna melakukan klik tombol simpan
 
        if($method=="POST"){
            //cara symfony menghandle data dari POST Parameter
            /*
                nama dan noTelepon adalah nama textbox di twig
            */

            $nama=$request->request->get("nama");
            $noTelepon=$request->request->get("noTelepon");
            $alamat=$request->request->get("alamat");
            
            //validasi jika nama anggota kosong
            if(empty($nama)){
                
                $error="Nama anggota masih kosong";

            }elseif(strlen($nama) <=2) {
            	$error="Nama anggota minimal tiga karakter";
						
            }elseif(empty($noTelepon)){
                
                $error="No Telepon masih kosong";
            
            }elseif(strlen($noTelepon) <6){
                $error="No Telepon minimal tiga karakter";
            }elseif(empty($alamat)){
                $error="Alamat masih kosong";            	
            }elseif(strlen($alamat)<10){
                $error="Alamat minimal sepulu karakter";            
            }

            else{

                //data yang akan diubah atau disimpan
                $data=array("id"=>$id_anggota,
                            "nama"=>$nama,
                            "noTelepon"=>$noTelepon,"alamat"=>$alamat);
                
                // memanggil function untuk save atau edit data. Ada di file /Service/anggotaService.php                
                $saveanggota=$this->anggotaService->saveOrEdit($data);

                if($saveanggota["level"]=="error"){
                    $error=$saveanggota["errMessage"];
                }else{
                    //jika save atau edit berhasil kembali ke halaman anggota
                    return new RedirectResponse($this->router->generate('anggota'));                    
                }
            }
        }


        //untuk pangination menggunakan knpBundles
        $anggota=$this->paginator->paginate(
                        $anggota,$request->query->get('page',1),3
                    );
        
        //variable yang dikirim ke twig
        $result=array("success"=>true,
                      "anggota"=>$anggota,
                      "method"=>$method,
                      "pageName"=>"Anggota",
                      "nama"=>$nama,
                      "noTelepon"=>$noTelepon,
                      "alamat"=>$alamat
                    );

		$sessionDelete=$this->session->get("deleteAnggota");
				
        if($currentRoute=="anggota_delete_error" && !empty($sessionDelete) && $sessionDelete["level"]=="error"){
        	$error=$sessionDelete["errMessage"];
			
        }else{
        	$this->session->remove("deleteAnggota");
        }

        //jika ada error kasih response success=false, dan jenis errornya
        if(!empty($error)){
            $result["success"]=false;
            $result["error"]=$error;
        }

        return $result;
    }

    /**
     * @Route("/anggota/delete/{id_anggota}", name="anggota_delete")
     * @Method({"GET","POST"})
     */
    public function anggotaDeleteAction($id_anggota="") {
        $result=$this->anggotaService->delete($id_anggota);
		if($result["level"]=="success"){
	        return new RedirectResponse($this->router->generate('anggota'));                    
		}else{
			$this->session->set("deleteAnggota",$result);
	        return new RedirectResponse($this->router->generate('anggota_delete_error'));                    			
		}    
		
		
    }


}

src/Perpustakaan/AnseraBundle/Resources/views/Anggota/anggota.html.twig
{% extends "::base.html.twig" %}
{% block body %}

{% include "adminheader.html.twig" %}

<!-- Container -->
<div id="container">
	<div class="shell">
				
		<!-- Message OK -->		
		{% if success==true and method == "POST" %}
		<div class="msg msg-ok">
			<p><strong>Data anggota sudah disimpan</strong></p>
		</div>
		{% endif %}

		<!-- End Message OK -->		

		{% if success==false %}		
		<!-- Message Error -->
		<div class="msg msg-error">
			<p><strong>{{ error }} </strong></p>
		</div>
		<!-- End Message Error -->
		{% endif %}

		<br />
		<!-- Main -->
		<div id="main">
			<div class="cl">&nbsp;</div>
			
			<!-- Content -->
			<div id="content">
				
				<!-- Box -->
				<div class="box">
					<!-- Box Head -->
					<div class="box-head">
						<h2 class="left">Anggota</h2>
					</div>
					<!-- End Box Head -->	

					<!-- Table -->
					<div class="table">
						<table width="100%" border="0" cellspacing="0" cellpadding="0">
							<tr>
								<th>No</th>
								<th>Nama</th>
								<th>Tanggal Bergabung</th>
								<th>No Telepon</th>
								<th>Alamat</th>
								<th width="110" class="ac">Aksi</th>
							</tr>
						 {% for ag in anggota %}
							<tr>
								<td>{{ ag.no }}</td>
								<td>{{ ag.nama}}</td>
								<td>{{ ag.tanggalBergabung | date("m/d/Y")}}</td>
								<td>{{ ag.noTelepon }}</td>
								<td>{{ ag.alamat }}</td>								
								<td><a onclick="return confirm('Anda yakin akan menghapus record ini?')" href="{{ path('anggota_delete',{'id_anggota':ag.id})}}" class="ico del">Delete</a><a href="{{ path('anggota_edit',{'id_anggota':ag.id})}}" class="ico edit">Edit</a></td>
							</tr>
						{% endfor %}
						</table>
						
						
						<!-- Pagging -->
						<div class="pagging">
							<!-- cara menggunakan library knp_pagination -->
							{{ knp_pagination_render(anggota) }}

						</div>
						<!-- End Pagging -->
						
					</div>
					<!-- Table -->
					
				</div>
				<!-- End Box -->
				
				<!-- Box -->
				<div class="box">
					<!-- Box Head -->
					<div class="box-head">
						<h2>Tambah Anggota</h2>
					</div>
					<!-- End Box Head -->
					<!-- menentukan action url. jika ada id_anggota berarti arahkan ke url /anggota/edit -->
					{% if app.request.get('id_anggota') %}
						{% set url=path('anggota_edit',{'id_anggota':app.request.get('id_anggota')}) %}
					{% else %}
						{% set url=path('anggota') %}
					{% endif %}

					<form action="{{ url }}" method="post">
						
						<!-- Form -->
						<div class="form">
								<p>
									<span class="req">max 100 symbols</span>
									<label>Nama<span>(Required Field)</span></label>
									<input type="text" name="nama" value="{{ nama | default('') }}"class="field size1" />
								</p>	
								<p>
									<span class="req">max 100 symbols</span>
									<label>No Telepon<span>(Required Field)</span></label>
									<input type="text" name="noTelepon" value="{{ noTelepon | default('') }}"class="field size1" />
								</p>	

								<p>
									<span class="req">max 100 symbols</span>
									<label>Alamat <span>(Required Field)</span></label>
									<textarea name="alamat" class="field size1">{{ alamat }}</textarea>
								</p>	

							
						</div>
						<!-- End Form -->
						
						<!-- Form Buttons -->
						<div class="buttons">
							<input type="submit" class="button" value="SIMPAN" />
						</div>
						<!-- End Form Buttons -->
					</form>
				</div>
				<!-- End Box -->

			</div>
			<!-- End Content -->
			
			
			<div class="cl">&nbsp;</div>			
		</div>
		<!-- Main -->
	</div>
</div>
<!-- End Container -->

<!-- End Container -->
{% endblock %}